article/urls.py
from django.contrib import admin
from django.urls import path

import article.views
app_name="article" # istediyimiz ad ola biler

from article import views
urlpatterns = [
    
  
    path('', views.articles,name="articles"),
    path('dashboard',views.dashboard,name="dashboard"),
    path('comment/<int:id>',views.addComment,name="comment"),
    path('article/<int:id>', views.articledetail,name="articledetail"),
    path('addArticle',views.addArticle,name="addArticle"),
    path('delete/<int:id>', views.deleteArticle,name="deleteArticle"),
    path('update/<int:id>', views.updateArticle,name="updateArticle"),
    
]

blogDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),

    path('about-us/',views.about,name="about"),
    path('user/',include("user.urls")),

    path('articles/',include("article.urls"))

       # path('articles/<int:id>',views.articleDetail,name="articleDetail"),#esasda bununcun
    # path('articles/tst1',views.articleDetail,name="articleDetail"),
    # path('articles/tst2',views.articleDetail,name="articleDetail"),
    # path('articles/tst3',views.articleDetail,name="articleDetail"),
    # path('articles/tst4',views.articleDetail,name="articleDetail"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path


app_name="user" # istediyimiz ad ola biler

from user import views
urlpatterns = [
    path('register/', views.registerUser,name="register"),
    path('login/', views.loginUser,name="login"),
    path('logout/', views.logoutUser,name="logout"),

]

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Blog Django</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> 
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Ana Səhifə</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'article:articles' %}">Məqalələr</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'about' %}">Haqqımızda</a>
          </li>
      </ul>
 
      <ul class="navbar-nav ml-auto">
     {% if request.user.is_authenticated %}
          <li class="nav-item ">
              <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
          </li>
          <li class="nav-item ">
              <a class="nav-link" href="{% url 'user:logout' %}">Çıxış</a>
          </li>
     {% else %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'user:login' %}">Giriş</a>
          </li>
          <li class="nav-item ">
              <a class="nav-link" href="{% url 'user:register' %}">Qeydiyyat</a>
          </li>
     {% endif %}
      
           
        </ul>
      
    </div>
  </nav>