article/urls.py
from django.contrib import admin
from django.urls import path

import article.views
app_name="article" # istediyimiz ad ola biler

from article import views
urlpatterns = [
    
  
    path('', views.articles,name="articles"),
    path('dashboard',views.dashboard,name="dashboard"),
    path('comment/<int:id>',views.addComment,name="comment"),
    path('article/<int:id>', views.articledetail,name="articledetail"),
    path('addArticle',views.addArticle,name="addArticle"),
    path('delete/<int:id>', views.deleteArticle,name="deleteArticle"),
    path('update/<int:id>', views.updateArticle,name="updateArticle"),
    
]

blogDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),

    path('about-us/',views.about,name="about"),
    path('user/',include("user.urls")),

    path('articles/',include("article.urls"))

       # path('articles/<int:id>',views.articleDetail,name="articleDetail"),#esasda bununcun
    # path('articles/tst1',views.articleDetail,name="articleDetail"),
    # path('articles/tst2',views.articleDetail,name="articleDetail"),
    # path('articles/tst3',views.articleDetail,name="articleDetail"),
    # path('articles/tst4',views.articleDetail,name="articleDetail"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path


app_name="user" # istediyimiz ad ola biler

from user import views
urlpatterns = [
    path('register/', views.registerUser,name="register"),
    path('login/', views.loginUser,name="login"),
    path('logout/', views.logoutUser,name="logout"),

]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):

    author=models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="Yazar")
    title=models.CharField(max_length=50,verbose_name="Başlıq")
    content=RichTextField("Məzmun")
    article_image=models.FileField(blank=True,null=True,verbose_name="Şəkil")
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="Yaradılma Tarixi") 
    updated_at=models.DateTimeField(auto_now_add=True,verbose_name="Yenilənmə Tarixi")
        #bu asagidaki kod ilk basda menasiz gelirdi lakin indi commentle elaqe yarananda onun foreing key olaraq goturende adi article object kimi yox ele title kimi gelir aydin basa dusmek olur
    def __str__(self):
        return self.title 
    class Meta: # tarixe gore siralama
        ordering = ['-created_at']
class Comment(models.Model): 
    article=models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Məqalə",related_name="comments")
    comment_author=models.CharField(max_length=50,verbose_name="Ad Soyad")
    comment_content=models.CharField(max_length=200,verbose_name="Şərh")
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="Yaradılma Tarixi") 
    class Meta:
        ordering = ['-created_at']

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    
    class Meta: #bu sayede birde custom form yaratmiriq modeli olanlarinki cox qisa kodla yaranmis olur
        model=Article
        fields=["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .models import Article,Comment

from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):

    # return HttpResponse("Ana Səhifə")
    return render(request,'index.html',{"number":7}) #laraveldeki kimi

def about(request):

    return render(request,'about.html')








def articles(request):

    keyword=request.GET.get("keyword")

    if keyword:
        articles=Article.objects.filter(title__contains=keyword) #like sql emeliyati 
        return render(request,"articles.html",{"articles":articles})
    articles=Article.objects.all()
    return render(request,"articles.html",{"articles":articles})


@login_required(login_url = "user:login")
def dashboard(request):

    articles=Article.objects.filter(author=request.user)
    context={
        "articles":articles
    }
    return render(request,"dashboard.html",context)

def articledetail(request,id):

    # article=Article.objects.filter(id=id).first()
    
    article=get_object_or_404(Article,id=id) # obyekt yoxdursa 404 sehifesi acilir
    
    comments=article.comments.all()

    context={
        "article":article,
        "comments":comments
    }


    return render(request,"articledetail.html",context)






@login_required(login_url = "user:login")
def addArticle(request):
    form=ArticleForm(request.POST or None,request.FILES or None) # sekile gore
    context={
        "form":form
    }
    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,"Məqalə uğurla yaradıldı!")
        return redirect("article:dashboard")
    
    return render(request,"addarticle.html",context)

@login_required(login_url = "user:login")
def updateArticle(request,id):
    article=get_object_or_404(Article,id=id)
    form=ArticleForm(request.POST or None,request.FILES or None,instance=article) # icerisine elave edir
    if form.is_valid():
        article=form.save(commit=False)
        article.author=request.user
        article.save()
        messages.success(request,"Məqalə uğurla yeniləndi!")
        return redirect("article:dashboard")
        
    context={
        "form":form
    }
    return render(request,"update.html",context)

@login_required(login_url = "user:login") # burdaki user urls of userdeki appname nedirse onu yazmaliyiq
def deleteArticle(request,id):
    article=get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Məqalə uğurla silindi")
    return redirect("article:dashboard")


def addComment(request,id):
    article =get_object_or_404(Article,id=id)

    if request.method=='POST':
        comment_author=request.POST.get("comment_author")
        comment_content=request.POST.get("comment_content")
        newComment=Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article=article
        newComment.save()

        
    return redirect(reverse("article:articledetail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}

{% block body %}

<h1 class="display-4 mt-5">Haqqımızda</h1>
<hr>
<p>

<b>✦ Blog Django’nınn quruluşu</b><br>

2018-ci ilin Sentyabr ayında Əli Kəlbəliyev tərəfindən qurulan Blog Django’nun internet mühitində dünyadakı dəyişiklikləri incələyərək analiz edən və Azərbaycanda fəaliyyət göstərən Bloq saytıdır. Bizim bloqumuzda bir çox kateqoriyalarda ( Texnologiya, Səyahət, Yaşam və b.) məqalələr, bir çox akademik şəxslərin fikirlırərini və bəzi tövsiyyələri görə bilərsiniz. Blog Django'nun məqsədi tam olaraq oxucuları vacib informasiyalarla təmin etməkdir.
<br>
<br>
<b>✦ Biz kimik?</b><br>
Günümüzdə ən vacib şeylərdən biri informasiyadır. Biz bu bloqda sizlərə öyrəndiyimiz, təcrübələrimiz və sizə lazım ola biləcək informasiyaları çatdırmaq üçün çalışırıq.
Bloqdakı məqalələr bir neçə nəfərlik heyyət tərəfindən yazılır. Bundan əlavə qonaq yazarlarımızda mövcuddur.
</p>

{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags%}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <h3  class="mt-5" >Məqalə yazın!</h3> 
        <hr>
        <form method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            {{form.media}}
            {{form| crispy}}

            <button type="submit" class="btn btn-danger" > Yarat </button>

        </form>
    </div>
</div>



{% endblock body %}

templates/articledetail.html
{% extends "layout.html" %}
{% block body %}

<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-12">

        <!-- Title -->
        <h1 class="mt-4">{{article.title}}</h1>

        <!-- Author -->
        <p class="lead">
          Yazar: {{article.author.username}}
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Tarix: {{article.created_at}}</p>

        <hr>
      {% if article.article_image %}
      <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">

        <hr>
      
      {% endif %}
        

        <!-- Post Content -->
        <p class="lead">{{article.content|safe}}</p> 
        {% comment %} ck editorde ki yazilisini gostermek ucun safe {% endcomment %}

        
        <hr>

    
            {% comment %} Comment show  {% endcomment %}
        {% if comments %}
        <h3>Şərhlər</h3><hr><br>
          {% for comment in comments %}
          
                <div class="media mb-4">
                  <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                  <div class="media-body">
                    <h5 class="mt-0">{{comment.comment_author}}</h5>
                    {{comment.comment_content}}
                    <p style="float:right" >{{comment.created_at}}</p>
                  </div>
                </div>
          {% endfor %}
        {% else %}
        <div class="alert alert-warning" >Bu məqalədə hələki şərh yoxdur...</div>
        {% endif %}

{% comment %} Comment form {% endcomment %}
          <div class="card my-4">
              <h5 class="card-header">Buradan fikrinizi bölüşə bilərsiniz..</h5>
              <div class="card-body">
                <form action="{% url 'article:comment' article.id %}" method="POST" >
                   {% csrf_token %}  
                    <div class="form-group">
                      <label for="name-comment">Ad Soyad</label>
                      <input type="text" class="form-control" id="name-comment" name="comment_author" placeholder="Əli Kəlbəliyev">
                    </div>
                  <div class="form-group">
                    <label for="content-comment">Şərhiniz</label>
                    <textarea id="content-comment" class="form-control" name="comment_content" rows="3"></textarea>
                  </div>
                  <button type="submit" class="btn btn-danger">Yaz</button>
                </form>
              </div>
            </div>
      
    </div>
</div>



     
     

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}

    <h3 class="mt-5">Məqalələr</h3>
    <hr>
    {% if articles %}
            <form >
            {% csrf_token %}
            <input type="text" name="keyword" max-length="50" placeholder="Məqalənin adını yazın.." class="col-md-9">
            <button type="submit" class="btn btn-danger">Axtar</button>
            </form>
        {% for article in articles %}
            <div class="row">

      <!-- Post Content Column -->
            <div class="col-lg-8">


            <!-- Title -->
            <h3 class="mt-4"><a href="{% url 'article:articledetail' article.id  %}">{{article.title}}</a></h3>
             
            {% if article.article_image %}
            <!-- Preview Image -->
               <a href="{% url 'article:articledetail' article.id  %}"> <img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>

            
            {% endif %}
             <p class="lead">{{article.content|safe|truncatewords:5}} <a style="float:right" class="btn btn-danger" href="{% url 'article:articledetail' article.id  %}">Davamını oxu</a></p> 
            <!-- Author -->
            <p class="lead">
             {{article.author.username}} - {{article.created_at}}
            </p>


        <hr>
        <br>
      

    </div>
</div>
        {% endfor %}
    {% else %}
    <div class="alert alert-warning" >Məqalə tapılmadı..</div>
    {% endif %}
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3 class="mt-5">Kontrol Paneli</h3>
<hr>
<p>Xoşgəldiniz,<small>{{request.user.username}}</small></p>
<hr>

<a class="btn btn-danger" href="/articles/addArticle">Məqalə Yaz</a>
<hr>
{% if articles %}
    <table class="table table-dark">
        <thead>
            <tr>
            <th scope="col">id</th>
            <th scope="col">Başlıq</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarix</th>
            <th scope="col">Yenilə</th>
            <th scope="col">Sil</th>
            </tr>
        </thead>
        <tbody>
  {% for article in articles %}
  
  
            <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:articledetail' article.id  %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_at}}</td>
            <td><a href="{% url 'article:updateArticle' article.id  %}" class="btn btn-warning">Yenilə</a></td>
            <td><a href="{% url 'article:deleteArticle' article.id  %}" class="btn btn-danger">Sil</a></td>
            </tr>
  {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="alert alert-warning"> Sizin tərəfinizdən yazılmış heç bir məqalə yoxdur.. </div>
{% endif %}

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center mt-5"> 
{% comment %} Burdaki jumbotron xususi dizayndi {% endcomment %}
    <h3 class="display-4" >Ana Səhifə</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos iure libero adipisci, sed, dolor, assumenda aliquam voluptas natus saepe quibusdam aperiam nulla blanditiis tempora possimus rem laboriosam architecto fuga repudiandae.</p>
</div>

<p>
 {% if request.user.is_authenticated %}
      Giriş Yapılmış - {{request.user.username}}
      {% else %}
      Giriş yapılmamış  
      {% endif %}

</p>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog Django</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">    
</head>
<body>

    <header>
    
        {% include "includes/navbar.html" %}
        {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "info" %}
                        <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endif %}
                {% endfor %}
        {% endif %}
    </header>

    <div class="container">

        {% block body %}
        
        {% endblock body %}
    </div>

        


<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3 class="mt-5">Giriş</h3>
        <hr>

{% comment %} crispy formlar ile dizayn etmek olur   {% endcomment %}
        <form  method="POST">

            {% csrf_token %}
            {% comment %} {{form.as_p}} {% endcomment %}
            {{form|crispy}}
            <button type="submit" class="btn btn-danger" > Daxil ol </button>
        </form>
    
    </div>
</div>
{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3 class="mt-5">Qeydiyyat</h3>
        <hr>

{% comment %} crispy formlar ile dizayn etmek olur   {% endcomment %}
        <form  method="POST">

            {% csrf_token %}
            {% comment %} {{form.as_p}} {% endcomment %}
            {{form|crispy}}
            <button type="submit" class="btn btn-danger" > Qeyd ol </button>
        </form>
    
    </div>
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags%}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <h3  class="mt-5" >Məqalə Yenilə</h3> 
        <hr>
        <form method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            {{form.media}}
            {{form| crispy}}

            <button type="submit" class="btn btn-danger" > Yenilə </button>

        </form>
    </div>
</div>



{% endblock body %}